language: node_js
node_js:
  - '6.3.0'

before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

before_script:
  - npm install
  - npm start > /dev/null &
  - sleep 1

script:
  - npm test -- --browsers=Firefox --single-run
  - npm run protractor -- --browser=firefox
